import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { authenticateToken } from '../middlewares/auth.js';
import { requireAdmin, requireSuperAdmin } from '../middlewares/roleCheck.js';
import { upload } from '../middlewares/upload.js';
import { asyncHandler as wrap } from '../middlewares/errorHandler.js';
import * as auth from '../controllers/authController.js';
import * as users from '../controllers/userController.js';
import * as admins from '../controllers/adminController.js';
import * as books from '../controllers/bookController.js';
import * as inventory from '../controllers/inventoryController.js';
import * as operations from '../controllers/operationsController.js';
import * as reports from '../controllers/reportController.js';
const router = Router();
const loginLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 20, standardHeaders: 'draft-8', legacyHeaders: false, message: { error: 'Too many login attempts; try later' } });
router.post('/login', loginLimit, wrap(auth.login));
router.post('/enquiries', rateLimit({ windowMs: 3600000, limit: 5 }), wrap(reports.createEnquiry));
router.use(authenticateToken);
router.get('/reports', requireAdmin, wrap(reports.listReports));
router.post('/reports', rateLimit({ windowMs: 60000, limit: 10 }), wrap(reports.createReport));
router.put('/reports/:id', requireAdmin, wrap(reports.updateReport));
router.get('/me', wrap(auth.me));
router.post('/logout', wrap(auth.logout));
router.get('/users', requireAdmin, wrap(users.listUsers));
router.post('/users', requireAdmin, wrap(users.createUser));
router.put('/users/:id', wrap(users.updateProfile));
router.put('/users/:id/profile', wrap(users.updateProfile));
router.put('/users/:id/password', wrap(users.changePassword));
router.post('/users/:id/reset-password', requireSuperAdmin, wrap(users.resetPassword));
router.put('/users/:id/fees', requireSuperAdmin, wrap(users.updateFees));
router.put('/users/:id/permissions', requireSuperAdmin, wrap(users.updatePermissions));
router.delete('/users/:id', requireSuperAdmin, wrap(users.deleteUser));
router.get('/admins', requireSuperAdmin, wrap(admins.listAdmins));
router.post('/admins', requireSuperAdmin, wrap(admins.createAdmin));
router.delete('/admins/:id', requireSuperAdmin, wrap(admins.deleteAdmin));
router.get('/books', wrap(books.listBooks));
router.post('/books', requireAdmin, rateLimit({ windowMs: 60000, limit: 10 }), upload.single('pdf'), wrap(books.createBook));
router.get('/books/:id/pages/:page', rateLimit({ windowMs: 60000, limit: 60 }), wrap(books.deliverPage));
router.delete('/books/:id', requireSuperAdmin, wrap(books.deleteBook));
router.get('/inventory', requireAdmin, wrap(inventory.listInventory));
router.post('/inventory', requireAdmin, wrap(inventory.createInventory));
router.get('/transactions', requireAdmin, wrap(inventory.listTransactions));
router.post('/transactions', requireAdmin, wrap(inventory.createTransaction));
router.get('/visitors', requireAdmin, wrap(operations.listVisitors));
router.post('/visitors', requireAdmin, wrap(operations.createVisitor));
router.get('/settings', wrap(operations.getSettings));
router.put('/settings', requireSuperAdmin, wrap(operations.updateSettings));
router.get('/logs', requireSuperAdmin, wrap(operations.listLogs));
// Audit history has no client write or deletion endpoint.
export default router;
